# Generated by Django 6.0.1 on 2026-01-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('content_yaml', models.TextField(help_text='\nYAML defining template variables for this page\n\nYAML authoring rules (important)\nGive editors simple rules:\n✅ Multiline text\nsection_text: |\n  Line one\n  Line two\n✅ Lists\nfeatures:\n  - Fast\n  - Simple\n  - Reliable\n✅ Nested blocks\nhero:\n  title: Welcome\n  subtitle: Hello world\nTemplate:\n{{ hero.title }}\n\n')),
            ],
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
            ],
        ),
    ]
